// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxyahpherqsjskofjoga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4eWFocGhlcnFzanNrb2Zqb2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjMyNDMsImV4cCI6MjA3MDEzOTI0M30.xY2ltYVyP9jUhuX-NT8Cm8QJKa0kPje0tGGxzEBLYMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});